### ISSUE TITLE
Click event meta data

### ISSUE THREAD

**Issue by Rinbo** [Tmw/linreg#2]
The phx-click event on the svg-element sent me an empty map in my version of Phoenix LiveView (0.13.0). I solved it by modifying the LiveSocket instantiation in app.js:

```
let liveSocket = new LiveSocket("/live", Socket, {
  params: { _csrf_token: csrfToken },
  metadata: {
    click: (e, el) => {
      return {
        offsetX: e.offsetX,
        offsetY: e.offsetY,
      };
    },
  },
});
```
Thought I'd share since it wasn't obvious from the docs.

**Comment by Tmw** [comment]
Hey @Rinbo thanks for pointing this out! Indeed, the default behaviour changed since Phoenix Live View 0.13.0 (See [changelog](https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md#0130-2020-05-21)). 

I've updated the master accordingly to use the latest Phoenix and Phoenix LiveView and included a troubleshooting section, crediting you, for those following the blogposts :)
